Mapping between the existing API and the new data model
eclipse-tractusx/vas-country-risk-backend pull request #24
Opened 2023-07-06 15:22 UTC by fabiodmota

---
title: '(feat): Mapping between the existing API and the new data model'
---

## Description

This PR introduces a new feature that creates a mapping between the existing API and the new data model to accommodate "Supplier" and "Customer" columns. This is in response to the issue [#21](https://github.com/eclipse-tractusx/vas-country-risk-backend/issues/21) in the vas-country-risk-backend repository.

Fixes #21 

## Pre-review checks

- [x] DEPENDENCIES are up to date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] Copyright and license header are present on all affected files

### Additional information

- To request a review, check out [who's involved](https://projects.eclipse.org/projects/automotive.tractusx/who) to see a list of contributors and committers
- Use the [mailing list](https://accounts.eclipse.org/mailing-list/tractusx-dev) if you are unsure, who to contact, or if want to engage in a general discussion
- Check out our guide on [how to contribute](https://eclipse-tractusx.github.io/docs/oss/how-to-contribute)
- Check out our [Release Guidelines](https://eclipse-tractusx.github.io/docs/release)
- Check out the [Eclipse Foundation contribution guidelines](https://www.eclipse.org/projects/handbook/#contributing)

2023-07-07 11:28 UTC, SebastianBezold commented on pom.xml
> +		<sonar.projectName>tx-vas-country-risk-backend</sonar.projectName>
Please prioritize eclipse-tractusx as leading repo. Therefore the naming should also follow Tractus-X. So maybe do not add the `tx-` prefix. You can add conditions to your workflows, that will configure the `sonar.projectName` via command parameter

2023-07-07 11:30 UTC, SebastianBezold approved these changes
Looks good from my side. Cannot evaluate the Java changes though

2023-07-07 13:53 UTC, fabiodmota commented
@SebastianBezold thank already changed the workflow for the sonar properties and changed the pom.xml if all its ok for you please accept this merge

2023-07-11 14:34 UTC, alexsilva-CGI commented
Tested application and it works fine, and Java code looks good. Ok from me

2023-07-12 11:08 UTC, SebastianBezold commented
Hi @fabiodmota, since my last review you pushed new code to this PR. They are even annotated as feature.
The PR is now of a size, that requires an IP check. I'll create the issue for that and link it here. 
Also, the `pom.xml` changed quite a bit and to me it seems like the spring-boot dependencies are new. The `DEPENDENCIES` file on the other hand hardly changed. Can you clarify that? Did you run dash? Do we need to open automated IP issues for the 3rd party dependencies?

2023-07-12 11:25 UTC, SebastianBezold requested changes
Beside the project content check that i'll create, see my review comments for potential changes

2023-07-12 11:25 UTC, SebastianBezold commented on src/main/java/org/eclipse/tractusx/valueaddedservice/config/WebClientConfiguration.java
Copyright and License header missing

2023-07-12 11:25 UTC, SebastianBezold commented on src/main/resources/config/application-dev.yml
> +    bpdmAddressUrl: 'https://business-partners.dev.demo.catena-x.net/companies/test-company/api/catena/output/addresses/search?limit=10'
Do you really need to specify this in the `application.yaml`? These are hard coded URLs to systems, that are not available for everyone. 
So please, if you are deploying your application, provide this as environment variables (spring boot picks that up for you) or any other option

2023-07-12 11:25 UTC, SebastianBezold commented on src/main/resources/config/application-int.yml
> +    bpdmAddressUrl: 'https://business-partners.int.demo.catena-x.net/companies/test-company/api/catena/output/addresses/search?limit=10'
See my other comment on hard coded config

2023-07-12 11:25 UTC, SebastianBezold commented on src/test/java/org/eclipse/tractusx/valueaddedservice/service/logic/CountryLogicServiceTest.java
> +
Unnecessary space

2023-07-12 11:25 UTC, SebastianBezold commented on src/test/java/org/eclipse/tractusx/valueaddedservice/utils/DataBaseJsonConverterTest.java
> +
Space?

2023-07-12 11:25 UTC, SebastianBezold commented on src/test/resources/config/application.yml
> +    token-url: https://centralidp.dev.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token
again hard coded config. To me it seems like a dangerous assumption, that the linked systems are always up. If this is for your tests, consider to switch to a scenario, that is fully under your control. Limit external dependencies

2023-07-12 11:26 UTC, SebastianBezold commented
Project content review: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9367

2023-07-12 13:16 UTC, fabiodmota commented
> Hi @fabiodmota, since my last review you pushed new code to this PR. They are even annotated as feature. The PR is now of a size, that requires an IP check. I'll create the issue for that and link it here. Also, the `pom.xml` changed quite a bit and to me it seems like the spring-boot dependencies are new. The `DEPENDENCIES` file on the other hand hardly changed. Can you clarify that? Did you run dash? Do we need to open automated IP issues for the 3rd party dependencies?

Just updated DEPENDENCIES file , every dependency is approved so i suppose it will not need dependency IP check

2023-07-12 14:13 UTC, SebastianBezold approved these changes

2023-07-12 14:14 UTC, SebastianBezold commented
Thx for the changes @fabiodmota !

2023-07-12 14:14 UTC, merged